### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by mattcollier**
This is currently configured to use beta.authn.io, not a local authorization.io.  Once we have a working dev local wallet we can switch it.  The credential request flow completes successfully.

Moving this on to the UI department.

@JoshDunnDev It is my intention that this should be as close to developing with Bedrock as possible.  It has quasar etc.  I expect that you'll be able to add pages and adjust the CHAPI flows as necessary.

### CODE REVIEW

**Review by dlongley — APPROVED** [review]
LGTM as a first cut. It needs to run on https, however, or CHAPI won't work properly. This reminds me to file a bug on the CHAPI polyfill so that it doesn't even get exposed in a non-secure context (as opposed to relying on browser blocking to do the job).

**Comment by mattcollier** [comment]
@dlongley I was wondering about https.  The CHAPI stuff *does* work as is however.  I've been using Firefox to test?

I was imagining that we might deploy this by terminating https nginx.

**Comment by dlongley** [comment]
@mattcollier, well sounds like I will need to fix the bug sooner rather than later then.

**Comment by mattcollier** [comment]
@dlongley just tested with Chrome as well and it works fine.  As in... a credential request from the wallet work.

**Pull request merged**
